### ISSUE TITLE
Gear with Alt Requirements Should be Equipable By Pets if Player Meets the Requirements

### ISSUE THREAD

**Issue by kinderghast** [IdleLands/IdleLands#771] opened 2017-07-26 22:57 UTC
At higher levels a lot of the good items found have alternate requirements (See #591) other than item score, however a player is unable to have their pet equip these items.

Should Pet.canEquipScore() check alternate requirements against the player to see if they can equip these items? The pets are constant companions, so the shared glory of achievements or statistics earned by the player could also apply to them?

**Comment by seiyria** [comment] 2017-07-26 23:02
Duplicate of #770.

**Closed by seiyria** 2017-07-26 23:02 UTC
