### ISSUE TITLE
Upgrade pet multiple times without losing gold

### ISSUE THREAD

**Issue by Leirbag2-D** [IdleLands/IdleLands#542] opened 2016-11-15 19:36 UTC
So i get 10k gold for the pet upgrade,Item find time i had only the gold necessary for it,and i bought it and i got to overview and i still had 10k gold,i got back to pets and i still could bought the others upgrades,and i did it and it counts i had the gold,and this just still happening,if im fast enough i can buy everything above the initial gold

**Comment by seiyria** [comment] 2016-11-15 19:37
duplicate of https://github.com/IdleLands/Play/issues/126

**Closed by seiyria** 2016-11-15 19:37 UTC
